import pandas as pd
import pickle

class Postprocessor():

    def __init__(self, predictions, id_keys,
                 species_path:str = "postprocess-speices"):
        """Stores prediction dataframe and the surveyId keys, reads in the
        pickled species Ids

        args:
            predictions         The predictions generated by the model, in the 
                                form of a dataframe containing boolean or 
                                boolean-like values
            id_keys             The surveyId values correlating with the 
                                predictions
            species_path        Path to the pickled list of all speciesIds
        """
        self.predictions = predictions
        self.id_keys = id_keys 
        with open(species_path, 'rb') as fp:
            self.species = pickle.load(fp)

    def process(self):
        """Loops through the generated predictions storing ids of the positive 
        occurences in a string for each unique surveyId

        return:
            pd.DataFrame        A dataframe containing the surveyIds and each
                                predicted species, stored as space separated 
                                strings
        """
        output_list = []
        for _, row in self.predictions.iterrows():
            row_string = ""
            for truth, value in zip(row, self.species):
                if truth:
                    row_string += str(value) + " "
            output_list.append(row_string)

        return pd.DataFrame({
            "surveyId"      : self.id_keys,
            "predictions"   : output_list
        })
    
    def save(self, filename:str):
        """Saves the dataframe as CSV to a specified location

        args:
            filename            The filepath in which to save the data
        """
        output = self.process()
        output.to_csv(filename, index=False)